"""add_page_model_for_dynamic_pages

Revision ID: 3f5e339efa0d
Revises: e241254a59e5
Create Date: 2026-02-06 20:31:28.087999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5e339efa0d'
down_revision: Union[str, None] = 'e241254a59e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('show_in_footer', sa.Boolean(), nullable=False),
    sa.Column('footer_order', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_index(op.f('ix_page_slug'), 'page', ['slug'], unique=True)
    op.create_index(op.f('ix_page_title'), 'page', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_title'), table_name='page')
    op.drop_index(op.f('ix_page_slug'), table_name='page')
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
