"""add_blacklisted_token_table

Revision ID: 7056decc07a3
Revises: 467164c1a7c2
Create Date: 2026-02-06 17:17:45.121351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7056decc07a3'
down_revision: Union[str, None] = '467164c1a7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_type', 'blacklisted_token', ['token', 'token_type'], unique=False)
    op.create_index(op.f('ix_blacklisted_token_id'), 'blacklisted_token', ['id'], unique=False)
    op.create_index(op.f('ix_blacklisted_token_token'), 'blacklisted_token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_token_token'), table_name='blacklisted_token')
    op.drop_index(op.f('ix_blacklisted_token_id'), table_name='blacklisted_token')
    op.drop_index('idx_token_type', table_name='blacklisted_token')
    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
