"""Add is_deleted to product and category

Revision ID: b55f5ee61a4c
Revises: 8b0ce4558cdc
Create Date: 2026-01-06 11:20:23.175920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55f5ee61a4c'
down_revision: Union[str, None] = '8b0ce4558cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deleted column with default False for existing rows
    op.add_column('category', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('product', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_deleted')
    op.drop_column('category', 'is_deleted')
    # ### end Alembic commands ###
